# Configuration file for AppVeyor CI
configuration: Release

image:
- Visual Studio 2019

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.6\mingw73_32
      CMAKE_GENERATOR: MinGW Makefiles
      MINGW_PATH: C:\Qt\Tools\mingw730_32

    #- QTDIR: C:\Qt\5.12.6\mingw73_64
    #  CMAKE_GENERATOR: MinGW Makefiles
    #  MINGW_PATH: C:\Qt\Tools\mingw730_64

# Parameters for default build commands (build_script is used instead).
build:

install:
- ps: |
    Set-Content -Path 'C:\Qt\5.12.6\mingw73_32\mkspecs\qconfig.pri' -Value 'QT_ARCH = i386
    QT_BUILDABI = i386-little_endian-ilp32
    QT.global.enabled_features = shared debug_and_release build_all c++11 c++14 c++1z c99 c11 thread future concurrent
    QT.global.disabled_features = cross_compile framework rpath appstore-compliant c++2a pkg-config force_asserts separate_debug_info simulator_and_device static
    QT_CONFIG += shared debug_and_release debug release build_all c++11 c++14 c++1z concurrent dbus no-pkg-config stl
    CONFIG += shared release no_plugin_manifest
    QT_VERSION = 5.12.6
    QT_MAJOR_VERSION = 5
    QT_MINOR_VERSION = 13
    QT_PATCH_VERSION = 2
    QT_GCC_MAJOR_VERSION = 7
    QT_GCC_MINOR_VERSION = 3
    QT_GCC_PATCH_VERSION = 0
    QT_EDITION = OpenSource
    QT_LICHECK =
    QT_RELEASE_DATE = 2019-10-28'
    
    Set-Content -Path 'C:\Qt\5.12.6\mingw73_32\bin\qt.conf' -Value '[Paths]
    Documentation=../../Docs/Qt-5.12.6
    Examples=../../Examples/Qt-5.12.6
    Prefix=..'
    Set-Content -Path 'C:\Qt\5.12.6\mingw73_32\bin\qtenv2.bat' -Value '@echo off
    echo Setting up environment for Qt usage...
    set PATH=C:\Qt\5.12.6\mingw73_32\bin;C:/Qt/Tools/mingw730_32\bin;%PATH%
    cd /D C:\Qt\5.12.6\mingw73_32'

- utils\appveyor\install.bat

before_build:
- utils\appveyor\before_build.bat

build_script:
- utils\appveyor\build_script.bat

after_build:
- utils\appveyor\after_build.bat

artifacts:
- path: 'copyq*.zip'
  name: CopyQ Portable

- path: 'copyq-*-setup.exe'
  name: CopyQ Setup

# Upload test log files.
on_finish:
- ps: Get-ChildItem -recurse -include copyq*.log* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
